### ISSUE TITLE
Error 'sorry, too many clients already'

### ISSUE THREAD

**Issue by asapostolov** [seeds-passport/seeds-autheticator#36]
In order to check if a token obtained in `/new` is signed on the blockchain, I'm using a script which checks `/check` endpoint every 1 second. At one point `/check` starts giving errors like this one
![image](https://user-images.githubusercontent.com/1162471/138557535-e5758eee-ccd8-40b0-8da7-daef71d27043.png)

Is there a limit of how many times we can call check? What is the intended way to use this endpoint besides pooling it every couple of seconds to see if the transaction got signed?

**Comment by cascalheira** [comment]
I will remove that for check.

**Comment by asapostolov** [comment]
This error was actually my issue with Postgres that was not connected to the API.

Still I was wondering weather might be a good idea to do `/check` on every request, to validate if the blockchain auth is still correct. That would mean a lot of requests for that endpoint.
